project_id = "vieaezhcsugfqvkgnuhm"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-manage-users]
verify_jwt = true

[functions.update-admin-password]
verify_jwt = true

[functions.public-claim-ticket]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.send-event-update]
verify_jwt = true

[functions.health-check]
enabled = true
verify_jwt = true
import_map = "./functions/health-check/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/health-check/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/health-check/*.html" ]
