project_id = "dmksigdpcbdvyejtedju"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-manage-users]
verify_jwt = true

[functions.update-admin-password]
verify_jwt = true

[functions.public-claim-ticket]
verify_jwt = false

[functions.send-event-update]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.export-attendees]
verify_jwt = true

[functions.create-payment-order]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
